services:
  - type: web
    name: school-admin-system
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn school_a.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: school-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: CSRF_TRUSTED_ORIGINS
        value: https://*.onrender.com

databases:
  - name: school-db
    databaseName: school
    user: school_user
